sm2::
	ln -f ../../../bhffer/public_html/app/sm2/README.md .
	ln -f ../../../bhffer/public_html/app/sm2/tests/*.html ./tests/
	ln -f ../../../bhffer/public_html/app/sm2/css/*.css ./css/
	ln -f ../../../bhffer/public_html/app/sm2/js/*.js ./js/
	ln -f ../../../bhffer/public_html/app/sm2/swf/*.swf ./swf/
	rsync -avz ../../../bhffer/public_html/app/sm2/image/* ./image/
