sm2::
	ln -f ../../../bhffer/public_html/app/sm2/*.html ./sm2/
	ln -f ../../../bhffer/public_html/app/sm2/README.md ./sm2/
	ln -f ../../../bhffer/public_html/app/sm2/swf/*.swf ./sm2/swf/
	$(MAKE) -C js
	$(MAKE) -C css

