window.domainMapDataArray__ = [
  {
    "name": "blog",
    "live": [
      "lurichardweb.site",
    ],
    "dead": [
      "lujunhong2or.com",
      "richardweblu.info",
      "blogwebrichardlu.top",
      "web2orrichardlu.one",
      "bloglurichardnet.site",
      "bloglunetmaster.com",
      "webmaster2orlu.online",
      "bloglumasterweb.org",
      "blogjunhonglunet.com",
      "webrichard2orlu.com",
      "richardlumaster.info",
      "blogjunhongmaster.org",
      "web2orjunhong.com",
      "webmaster2or.org",
      "blogweblumaster.org",
      "lumasterblog.org",
      "blogweblujunhong.net",
      "blogjunhongluweb.com",
      "webmaster2orlu.org",
      "blogjunhongweb.com",
      "blogwebrichardlu.org",
      "web2orrichardlu.com",
      "bloglunetrichard.com",
      "www.web2orlujunhong.org",
      "blogwebrichard.com",
      "blogjunhonglunet.org",
      "bloglumasterweb.net",
      "junhong2or.net",
      "web2orlujunhong.com",
      "net2orrichard.online",
      "bloglumasterweb.net",
    ]
  },
  {
    "name": "xlch",
    "live": [
      "xlch45.com",
    ],
    "dead": [
      "xlch44.com",
      "xlch43.com",
      "xlch42.com",
      "xlch41.com",
      "xlch40.com",
      "xlch39.com",
      "xlch38.com",
      "xlch37.com",
      "xlch36.com",
      "xlch35.com",
      "xlch34.com",
      "xlch33.com",
      "xlch32.com",
      "xlch31.com",
      "xlch30.com",
      "xlch29.com",
      "xlch28.com",
      "xlch27.com",
      "xlch26.com",
      "xlch25.com",
      "xlch24.com",
      "xlch23.com",
      "xlch22.com",
      "xlch21.com",
      "xlch20.com",
      "xlch19.com",
      "xlch18.com",
      "xlch17.com",
      "xlch16.com",
      "xlch15.com",
      "xlch14.com",
      "xlch13.com",
      "xlch12.com",
      "xlch11.com",
      "xlch10.com",
      "xlch9.com",
      "xlch8.com",
      "xlch7.com",
      "xlch6.com",
      "xlch5.com",
      "xlch4.com",
      "xlch3.com",
      "xlch2.com",
      "xlch1.com",
      "xlch.com",
      "xlch.org",
    ]
  },
  {
    "name": "mflh",
    "live": [
      "m.apple.haiweivipmflotuscibei.cloud/gegsyps/weibo",
      "support.haiweivipmflotuscibei.cloud/gegsyps/weibo",
      "tmall.haiweivipmflotuscibei.cloud/gegsyps/weibo",
    ],
    "dead": [
      "baidu.haiweivipmflotuscibei.cloud/gegsyps/weibo",
      "baidu.mfxlianhua.cloud/gegsyps/weibo",
      "vip.lianhuapureland.cloud/gegsyps/weibo",
      "vip.tech.mflianhua.cloud/gegsyps/weibo",
      "baidu.mflianhua.best/gegsyps/weibo",
      "m.sina.cbxs.mfchyuts.com/baidu/luntan/fofa1",
      "new.mfchyuts.com/baidu/luntan/fofa1",
      "m.baidu.mulotus.fabushi.cloud/baidu/luntan/fofa1",
      "baidu.new.mflotus.com/baidu/luntan/fofa1",
      "new.mflotus.com/baidu/luntan/fofa1",
      "mflotus.com/baidu/luntan/fofa1",
    ]
  },
  {
    "name": "caxl",
    "live": [
      "apple.caxlotus.com/fofa/bbs",
      "fab.blessedca.cloud/fofa/bbs",
      "awesome.blessedca.cloud/fofa/bbs",
      "baidu.lotusciai.cloud/fofa/bbs",
      "bbs.lotusciai.cloud/fofa/bbs",
    ],
    "dead": [
      "pro.blessedca.cloud/fofa/bbs",
      "adobe.caxlotus.com/fofa/bbs",
      "sina.meritlotus.cloud/fofa/bbs",
      "vip.gycciai.cloud/fofa/bbs",
      "vip.xlpureland.cloud/fofa/bbs",
      "sina.lotusciai.cloud/fofa/bbs",
      "vipbaidu.caxlotus.com/fofa/bbs",
      "vip.blessedca.cloud/fofa/bbs",
      "www.sina.caxlotus.com/fofa/bbs",
      "sina.caxlotus.com/fofa/bbs",
      "www.baidu.caxlotus.com/fofa/bbs",
      "baidu.caxlotus.com/fofa/bbs",
      "baidu.blisslotus.cloud/fofa/bbs",
    ]
  },
  {
    "name": "xlys",
    "live": [
      "ifeng.fofa.xlys.cloud",
      "baidu.fofa.xlys.cloud",
      "www.baidu.xlys2.live",
      //"baidu.xlbkqs.xlys.cloud",
    ],
    "dead": [
      "www.sohu.xlys.cloud",
      "baidu.xlys.live",
      "baidu.xlfmw.cloud",
      "baidu.xly2.cloud",
      "ifeng.xly2.cloud",
      "ifeng.xlfmw.cloud",
      "baidu.xlys.cloud",
      "baidu.xlys.cloud",
      "baidu.app.xlfmwang.org",
      "baidu.v.xlfmwang.org",
      "baidu.video.xlfmwang.org",
      "weibo.yun.xlfmwang.org",
      "www.xlfmwz.com",
      "xlfmwz.com",
    ]
  },
  {
    "name": "jchz",
    "live": [
      "women.wonderfulsummary.com/sinaweb/jchz",
    ],
    "dead": [
      "www.baidu.wonderfulsummary.com/sinaweb/jchz",
      "www.baidu.jchz68686568.com/sinaweb/jchz",
      "www.baidu.lujiajun8.com/sinaweb/jchz",
    ]
  },
  {
    "name": "balh",
    "live": [
      "www.baidu.balh2.live/cn/bbs",
    ],
    "dead": [
      "www.balh01.com/cn/bbs",
    ]
  },
  {
    "name": "xf123",
    "live": [
      "b.app.zgh1.com",
      "c.app.zgh1.com",
      "baidu.app.jhrt3.com",
      "baidu.app.ryt3.com",
      "app1.bhffrd.com",
    ],
    "dead": [
      "xf123.rf.gd",
      "bhff.infinityfreeapp.com/app",
      "xf8.great-site.net/app",
      "kindness.lovestoblog.com/app",
      "xf8.rf.gd",
      "xfabc.rf.gd",
      "xfabc.epizy.com/app",
      "cbxs.freecluster.eu/app",
    ]
  }
];
